[project]
name = "comfyui-n-nodes"
description = "A suite of custom nodes for ComfyUI that includes image captioning, LoadVideo, SaveVideo, LoadFramesFromFolder and FrameInterpolator"
version = "1.2.0"
license = { file = "LICENSE" }
dependencies = [
    "gitpython",
    "huggingface-hub",
    "moviepy<2",
    "opencv-python",
    "scikit-build",
    "timm==0.9.12",
    "transformers==4.36.2",
]

[project.urls]
Repository = "https://github.com/Nuked88/ComfyUI-N-Nodes"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "nuked"
DisplayName = "ComfyUI-N-Nodes"
Icon = ""
